# Site settings
title: SQ Values
header-img: img/home-bg.jpg
email: 
copyright_name: Every Nation Church Singapore.
description: "What is SQ? Think you’ve got SQ? Take a closer look."
baseurl: "/sqvalues"
url: "everynation.org.sg"
twitter_username: everynationsg
github_username:  raffypanes
facebook_username:  everynationsg
email_username:  

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
google_tracking_id: 

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
